# -*- coding: utf-8 -*-
"""Customer_Feedback_Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NjOAG5elLoXoBioM_FzpLdS3GzYaZqzL
"""

!pip install pandas matplotlib seaborn nltk wordcloud

# Import essential Python libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud

# Import NLP tools
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Download VADER sentiment lexicon
nltk.download('vader_lexicon')

# Import Google Colab's file upload utility
from google.colab import files

import pandas as pd
import io

# The CSV file has an unusual format where each line, including the header and data,
# is enclosed in an outer set of quotes, and then text fields inside are also quoted.

with open("/content/drive/MyDrive/DataSets/sentiment-analysis.csv", 'r') as f:
    raw_lines = f.readlines()

processed_lines = []

# Process header: Remove the outer quotes from the first line
# Example: '"Text, Sentiment, ..."\n' becomes 'Text, Sentiment, ...'
processed_lines.append(raw_lines[0].strip().strip('"'))

# Process data lines: Remove the outer quotes from each data line
# Example: '"""I love this product!"", Positive, ..."\n' becomes '"I love this product!", Positive, ...'
for line in raw_lines[1:]:
    processed_lines.append(line.strip().strip('"'))

# Join the processed lines back into a single string for pandas to read
csv_string = '\n'.join(processed_lines)

# Use io.StringIO to read this cleaned string as a CSV. pandas will handle the inner quotes.
df = pd.read_csv(io.StringIO(csv_string), sep=',')

# Show first few rows to verify parsing
df.head(10)

# Drop missing rows (if any)
df.dropna(inplace=True)

# Convert feedback text to lowercase (adjust column name if needed)
# Assuming 'Text' is the intended feedback column
df['Text'] = df['Text'].str.lower()

# Remove any trailing double quotes that resulted from the unusual CSV parsing
df['Text'] = df['Text'].str.rstrip('"')

df.head()

import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')

# Initialize sentiment analyzer
sia = SentimentIntensityAnalyzer()

# Apply VADER to each feedback in the 'Text' column
df['Sentiment_Score'] = df['Text'].apply(lambda x: sia.polarity_scores(x)['compound'])

# Categorize based on score
df['Sentiment'] = df['Sentiment_Score'].apply(
    lambda x: 'Positive' if x > 0.05 else ('Negative' if x < -0.05 else 'Neutral')
)

df.head()

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Use the 'Text' column for word cloud generation after cleaning
all_text = ' '.join(df['Text'])
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_text)

plt.figure(figsize=(10,5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title("Word Cloud of Feedback")
plt.show()

df.to_csv("customer_feedback_results.csv", index=False)

from google.colab import files
files.download("customer_feedback_results.csv")

positive = df[df['Sentiment'] == 'Positive'].shape[0]
negative = df[df['Sentiment'] == 'Negative'].shape[0]
neutral = df[df['Sentiment'] == 'Neutral'].shape[0]

summary = f"""
Customer Feedback Analysis Report
----------------------------------
Total Feedbacks: {len(df)}
Positive: {positive}
Negative: {negative}
Neutral: {neutral}

Overall Sentiment: {'Positive' if positive > negative else 'Negative' if negative > positive else 'Neutral'}
"""

print(summary)

with open("Customer_Feedback_Report.txt", "w") as f:
    f.write(summary)

files.download("Customer_Feedback_Report.txt")

